package com.sshtools.synergy.tests;

import java.io.IOException;

import org.junit.jupiter.api.extension.RegisterExtension;

import com.sshtools.client.SshClient;
import com.sshtools.client.SshClient.SshClientBuilder;
import com.sshtools.common.ssh.SshException;

/**
 * Base class for all integration tests.  Registers a shared {@link SshServerExtension}
 * that starts a real, in-process SSH server before the first test in the class
 * and stops it after the last.
 *
 * <p>Concrete test classes inherit the {@code SERVER} extension as well as the
 * {@link #connectWithPassword()} and {@link #connectWithPublicKey()} convenience
 * factories so they do not need to repeat connection boilerplate.
 */
public abstract class AbstractSshIntegrationTest {

    /**
     * Shared in-process SSH server.  Activated once per concrete test class by
     * the JUnit 5 {@code @RegisterExtension static} lifecycle.
     */
    @RegisterExtension
    protected static final SshServerExtension SERVER = new SshServerExtension();

    // -----------------------------------------------------------------------
    // Connection factories
    // -----------------------------------------------------------------------

    /**
     * Opens an authenticated connection to the test server using
     * password authentication.  The caller owns the returned client and must
     * close it (e.g. via try-with-resources).
     */
    protected SshClient connectWithPassword() throws IOException, SshException {
        return SshClientBuilder.create()
            .withHostname("127.0.0.1")
            .withPort(SERVER.getPort())
            .withUsername(SshServerExtension.TEST_USER)
            .withPassword(SshServerExtension.TEST_PASSWORD)
            .onConfigure(ctx -> ctx.setHostKeyVerification((host, pk) -> true))
            .build();
    }

    /**
     * Opens an authenticated connection to the test server using the
     * ephemeral public-key identity generated by {@link SshServerExtension}.
     */
    protected SshClient connectWithPublicKey() throws IOException, SshException {
        return SshClientBuilder.create()
            .withHostname("127.0.0.1")
            .withPort(SERVER.getPort())
            .withUsername(SshServerExtension.TEST_USER)
            .addIdentities(SERVER.getClientKeyPair())
            .onConfigure(ctx -> ctx.setHostKeyVerification((host, pk) -> true))
            .build();
    }
}
