package com.sshtools.synergy.tests;

/*-
 * #%L
 * Integration Tests
 * %%
 * Copyright (C) 2002 - 2026 JADAPTIVE Limited
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Lesser Public License for more details.
 * 
 * You should have received a copy of the GNU General Lesser Public
 * License along with this program.  If not, see
 * <http://www.gnu.org/licenses/lgpl-3.0.html>.
 * #L%
 */

import java.io.IOException;

import org.junit.jupiter.api.extension.RegisterExtension;

import com.sshtools.client.SshClient;
import com.sshtools.client.SshClient.SshClientBuilder;
import com.sshtools.common.ssh.SshException;

/**
 * Base class for all integration tests.  Registers a shared {@link SshServerExtension}
 * that starts a real, in-process SSH server before the first test in the class
 * and stops it after the last.
 *
 * <p>Concrete test classes inherit the {@code SERVER} extension as well as the
 * {@link #connectWithPassword()} and {@link #connectWithPublicKey()} convenience
 * factories so they do not need to repeat connection boilerplate.
 */
public abstract class AbstractSshIntegrationTest {

    /**
     * Shared in-process SSH server.  Activated once per concrete test class by
     * the JUnit 5 {@code @RegisterExtension static} lifecycle.
     */
    @RegisterExtension
    protected static final SshServerExtension SERVER = new SshServerExtension();

    // -----------------------------------------------------------------------
    // Connection factories
    // -----------------------------------------------------------------------

    /**
     * Opens an authenticated connection to the test server using
     * password authentication.  The caller owns the returned client and must
     * close it (e.g. via try-with-resources).
     */
    protected SshClient connectWithPassword() throws IOException, SshException {
        return SshClientBuilder.create()
            .withHostname("127.0.0.1")
            .withPort(SERVER.getPort())
            .withUsername(SshServerExtension.TEST_USER)
            .withPassword(SshServerExtension.TEST_PASSWORD)
            .onConfigure(ctx -> ctx.setHostKeyVerification((host, pk) -> true))
            .build();
    }

    /**
     * Opens an authenticated connection to the test server using the
     * ephemeral public-key identity generated by {@link SshServerExtension}.
     */
    protected SshClient connectWithPublicKey() throws IOException, SshException {
        return SshClientBuilder.create()
            .withHostname("127.0.0.1")
            .withPort(SERVER.getPort())
            .withUsername(SshServerExtension.TEST_USER)
            .addIdentities(SERVER.getClientKeyPair())
            .onConfigure(ctx -> ctx.setHostKeyVerification((host, pk) -> true))
            .build();
    }
}
